# Generated by Django 2.2.11 on 2020-03-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('publishingHouse', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('numberOfPages', models.SmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bookCondition', models.CharField(max_length=100)),
                ('image', models.TextField()),
                ('idKey', models.SmallIntegerField()),
            ],
        ),
    ]
